/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class verifiedJNI {
  public final static native void peer_set(long jarg1);
  public final static native long peer_get();
  public final static native int signup(long jarg1, long jarg2);
  public final static native int signin(long jarg1, long jarg2);
  public final static native int signout();
}
