/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: verified.i

package verified

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

var _wrap_Swig_free_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_verified_e8f0de5c4fff2cfa unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}
type SwigcptrPeer uintptr

func (p SwigcptrPeer) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPeer) SwigIsPeer() {
}

var _wrap_peer_signup_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_peer_signup(base SwigcptrPeer, _ uintptr, _ uintptr) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_peer_signup_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func (arg1 SwigcptrPeer) Signup(arg2 Std_string, arg3 Std_string) (_swig_ret int) {
	return _swig_wrap_peer_signup(arg1, arg2.Swigcptr(), arg3.Swigcptr())
}

var _wrap_peer_signin_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_peer_signin(base SwigcptrPeer, _ uintptr, _ uintptr) (_ SwigcptrStd_string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_peer_signin_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func (arg1 SwigcptrPeer) Signin(arg2 Std_string, arg3 Std_string) (_swig_ret Std_string) {
	return _swig_wrap_peer_signin(arg1, arg2.Swigcptr(), arg3.Swigcptr())
}

var _wrap_peer_signout_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_peer_signout(base SwigcptrPeer) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_peer_signout_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func (arg1 SwigcptrPeer) Signout() (_swig_ret int) {
	return _swig_wrap_peer_signout(arg1)
}

var _wrap_new_peer_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_new_peer() (base SwigcptrPeer) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_peer_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func NewPeer() (_swig_ret Peer) {
	return _swig_wrap_new_peer()
}

var _wrap_delete_peer_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_delete_peer(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_peer_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func DeletePeer(arg1 Peer) {
	_swig_wrap_delete_peer(arg1.Swigcptr())
}

type Peer interface {
	Swigcptr() uintptr
	SwigIsPeer()
	Signup(arg2 Std_string, arg3 Std_string) (_swig_ret int)
	Signin(arg2 Std_string, arg3 Std_string) (_swig_ret Std_string)
	Signout() (_swig_ret int)
}

type SwigcptrClient uintptr

func (p SwigcptrClient) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrClient) SwigIsClient() {
}

var _wrap_client_handleOutboundRequest_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_client_handleOutboundRequest(base SwigcptrClient, _ uintptr) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_client_handleOutboundRequest_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func (arg1 SwigcptrClient) HandleOutboundRequest(arg2 Client_request) (_swig_ret bool) {
	return _swig_wrap_client_handleOutboundRequest(arg1, arg2.Swigcptr())
}

var _wrap_client_handleInboundResponse_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_client_handleInboundResponse(base SwigcptrClient, _ uintptr) (_ bool) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_client_handleInboundResponse_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func (arg1 SwigcptrClient) HandleInboundResponse(arg2 Client_request) (_swig_ret bool) {
	return _swig_wrap_client_handleInboundResponse(arg1, arg2.Swigcptr())
}

var _wrap_new_client_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_new_client() (base SwigcptrClient) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_client_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func NewClient() (_swig_ret Client) {
	return _swig_wrap_new_client()
}

var _wrap_delete_client_verified_e8f0de5c4fff2cfa unsafe.Pointer

func _swig_wrap_delete_client(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_client_verified_e8f0de5c4fff2cfa, _swig_p)
	return
}

func DeleteClient(arg1 Client) {
	_swig_wrap_delete_client(arg1.Swigcptr())
}

type Client interface {
	Swigcptr() uintptr
	SwigIsClient()
	HandleOutboundRequest(arg2 Client_request) (_swig_ret bool)
	HandleInboundResponse(arg2 Client_request) (_swig_ret bool)
}


type SwigcptrClient_request uintptr
type Client_request interface {
	Swigcptr() uintptr;
}
func (p SwigcptrClient_request) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

