/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class client {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected client(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        verifiedJNI.delete_client(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class request {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected request(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(request obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          verifiedJNI.delete_client_request(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setRoot(SWIGTYPE_p_std__string value) {
      verifiedJNI.client_request_root_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__string getRoot() {
      return new SWIGTYPE_p_std__string(verifiedJNI.client_request_root_get(swigCPtr, this), true);
    }
  
    public void setType(SWIGTYPE_p_std__string value) {
      verifiedJNI.client_request_type_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__string getType() {
      return new SWIGTYPE_p_std__string(verifiedJNI.client_request_type_get(swigCPtr, this), true);
    }
  
    public void setVerifyingPeers(SWIGTYPE_p_std__vectorT_dht__InfoHash_t value) {
      verifiedJNI.client_request_verifyingPeers_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_dht__InfoHash_t.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__vectorT_dht__InfoHash_t getVerifyingPeers() {
      return new SWIGTYPE_p_std__vectorT_dht__InfoHash_t(verifiedJNI.client_request_verifyingPeers_get(swigCPtr, this), true);
    }
  
    public void setSendTo(SWIGTYPE_p_dht__InfoHash value) {
      verifiedJNI.client_request_sendTo_set(swigCPtr, this, SWIGTYPE_p_dht__InfoHash.getCPtr(value));
    }
  
    public SWIGTYPE_p_dht__InfoHash getSendTo() {
      return new SWIGTYPE_p_dht__InfoHash(verifiedJNI.client_request_sendTo_get(swigCPtr, this), true);
    }
  
    public void setFrom(SWIGTYPE_p_dht__InfoHash value) {
      verifiedJNI.client_request_from_set(swigCPtr, this, SWIGTYPE_p_dht__InfoHash.getCPtr(value));
    }
  
    public SWIGTYPE_p_dht__InfoHash getFrom() {
      return new SWIGTYPE_p_dht__InfoHash(verifiedJNI.client_request_from_get(swigCPtr, this), true);
    }
  
    public void setContractId(SWIGTYPE_p_std__string value) {
      verifiedJNI.client_request_contractId_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__string getContractId() {
      return new SWIGTYPE_p_std__string(verifiedJNI.client_request_contractId_get(swigCPtr, this), true);
    }
  
    public void setEncodedRequest(SWIGTYPE_p_std__string value) {
      verifiedJNI.client_request_encodedRequest_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__string getEncodedRequest() {
      return new SWIGTYPE_p_std__string(verifiedJNI.client_request_encodedRequest_get(swigCPtr, this), true);
    }
  
    public void setEncodedResponse(SWIGTYPE_p_std__string value) {
      verifiedJNI.client_request_encodedResponse_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
    }
  
    public SWIGTYPE_p_std__string getEncodedResponse() {
      return new SWIGTYPE_p_std__string(verifiedJNI.client_request_encodedResponse_get(swigCPtr, this), true);
    }
  
    public void setRequestorPeer(SWIGTYPE_p_dht__NodeExport value) {
      verifiedJNI.client_request_requestorPeer_set(swigCPtr, this, SWIGTYPE_p_dht__NodeExport.getCPtr(value));
    }
  
    public SWIGTYPE_p_dht__NodeExport getRequestorPeer() {
      return new SWIGTYPE_p_dht__NodeExport(verifiedJNI.client_request_requestorPeer_get(swigCPtr, this), true);
    }
  
    public void setResponderPeer(SWIGTYPE_p_dht__NodeExport value) {
      verifiedJNI.client_request_responderPeer_set(swigCPtr, this, SWIGTYPE_p_dht__NodeExport.getCPtr(value));
    }
  
    public SWIGTYPE_p_dht__NodeExport getResponderPeer() {
      return new SWIGTYPE_p_dht__NodeExport(verifiedJNI.client_request_responderPeer_get(swigCPtr, this), true);
    }
  
    public request() {
      this(verifiedJNI.new_client_request(), true);
    }
  
  }

  public boolean handleOutboundRequest(client.request arg0) {
    return verifiedJNI.client_handleOutboundRequest(swigCPtr, this, client.request.getCPtr(arg0), arg0);
  }

  public boolean handleInboundResponse(client.request arg0) {
    return verifiedJNI.client_handleInboundResponse(swigCPtr, this, client.request.getCPtr(arg0), arg0);
  }

  public client() {
    this(verifiedJNI.new_client(), true);
  }

}
