/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class verifiedJNI {
  public final static native int peer_signup(long jarg1, peer jarg1_, long jarg2, long jarg3);
  public final static native long peer_signin(long jarg1, peer jarg1_, long jarg2, long jarg3);
  public final static native int peer_signout(long jarg1, peer jarg1_);
  public final static native long new_peer();
  public final static native void delete_peer(long jarg1);
  public final static native void client_request_root_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_root_get(long jarg1, client.request jarg1_);
  public final static native void client_request_type_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_type_get(long jarg1, client.request jarg1_);
  public final static native void client_request_verifyingPeers_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_verifyingPeers_get(long jarg1, client.request jarg1_);
  public final static native void client_request_sendTo_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_sendTo_get(long jarg1, client.request jarg1_);
  public final static native void client_request_from_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_from_get(long jarg1, client.request jarg1_);
  public final static native void client_request_contractId_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_contractId_get(long jarg1, client.request jarg1_);
  public final static native void client_request_encodedRequest_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_encodedRequest_get(long jarg1, client.request jarg1_);
  public final static native void client_request_encodedResponse_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_encodedResponse_get(long jarg1, client.request jarg1_);
  public final static native void client_request_requestorPeer_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_requestorPeer_get(long jarg1, client.request jarg1_);
  public final static native void client_request_responderPeer_set(long jarg1, client.request jarg1_, long jarg2);
  public final static native long client_request_responderPeer_get(long jarg1, client.request jarg1_);
  public final static native long new_client_request();
  public final static native void delete_client_request(long jarg1);
  public final static native boolean client_handleOutboundRequest(long jarg1, client jarg1_, long jarg2, client.request jarg2_);
  public final static native boolean client_handleInboundResponse(long jarg1, client jarg1_, long jarg2, client.request jarg2_);
  public final static native long new_client();
  public final static native void delete_client(long jarg1);
}
