/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class verified {
  public static void setPeer(SWIGTYPE_p_class value) {
    verifiedJNI.peer_set(SWIGTYPE_p_class.getCPtr(value));
  }

  public static SWIGTYPE_p_class getPeer() {
    return new SWIGTYPE_p_class(verifiedJNI.peer_get(), true);
  }

  public static int signup(SWIGTYPE_p_string arg0, SWIGTYPE_p_string arg1) {
    return verifiedJNI.signup(SWIGTYPE_p_string.getCPtr(arg0), SWIGTYPE_p_string.getCPtr(arg1));
  }

  public static int signin(SWIGTYPE_p_string arg0, SWIGTYPE_p_string arg1) {
    return verifiedJNI.signin(SWIGTYPE_p_string.getCPtr(arg0), SWIGTYPE_p_string.getCPtr(arg1));
  }

  public static int signout() {
    return verifiedJNI.signout();
  }

}
