/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_VERIFIED_H
#define PHP_VERIFIED_H

extern zend_module_entry verified_module_entry;
#define phpext_verified_ptr &verified_module_entry

#ifdef PHP_WIN32
# define PHP_VERIFIED_API __declspec(dllexport)
#else
# define PHP_VERIFIED_API
#endif

ZEND_NAMED_FUNCTION(_wrap_peer_signup);
ZEND_NAMED_FUNCTION(_wrap_peer_signin);
ZEND_NAMED_FUNCTION(_wrap_peer_signout);
ZEND_NAMED_FUNCTION(_wrap_new_peer);
ZEND_NAMED_FUNCTION(_wrap_client_handleOutboundRequest);
ZEND_NAMED_FUNCTION(_wrap_client_handleInboundResponse);
ZEND_NAMED_FUNCTION(_wrap_new_client);
PHP_MINIT_FUNCTION(verified);

#endif /* PHP_VERIFIED_H */
