<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('verified')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_verified.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('verified.so')) return;
    } else {
      if (!dl('verified.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



/* PHP Proxy Classes */
class peer {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_verified_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_verified_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function signup($arg1,$arg2) {
		return peer_signup($this->_cPtr,$arg1,$arg2);
	}

	function signin($arg1,$arg2) {
		return peer_signin($this->_cPtr,$arg1,$arg2);
	}

	function signout() {
		return peer_signout($this->_cPtr);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_peer') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_peer();
	}
}

class client {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_verified_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_verified_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function handleOutboundRequest($arg1) {
		return client_handleOutboundRequest($this->_cPtr,$arg1);
	}

	function handleInboundResponse($arg1) {
		return client_handleInboundResponse($this->_cPtr,$arg1);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_client') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_client();
	}
}


?>
