# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_verified')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_verified')
    _verified = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_verified', [dirname(__file__)])
        except ImportError:
            import _verified
            return _verified
        try:
            _mod = imp.load_module('_verified', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _verified = swig_import_helper()
    del swig_import_helper
else:
    import _verified
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class peer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, peer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, peer, name)
    __repr__ = _swig_repr

    def signup(self, arg2, arg3):
        return _verified.peer_signup(self, arg2, arg3)

    def signin(self, arg2, arg3):
        return _verified.peer_signin(self, arg2, arg3)

    def signout(self):
        return _verified.peer_signout(self)

    def __init__(self):
        this = _verified.new_peer()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _verified.delete_peer
    __del__ = lambda self: None
peer_swigregister = _verified.peer_swigregister
peer_swigregister(peer)

class client(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, client, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, client, name)
    __repr__ = _swig_repr

    def handleOutboundRequest(self, arg2):
        return _verified.client_handleOutboundRequest(self, arg2)

    def handleInboundResponse(self, arg2):
        return _verified.client_handleInboundResponse(self, arg2)

    def __init__(self):
        this = _verified.new_client()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _verified.delete_client
    __del__ = lambda self: None
client_swigregister = _verified.client_swigregister
client_swigregister(client)

# This file is compatible with both classic and new-style classes.


